# Generated by Django 2.1.7 on 2023-07-16 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateTimeField(blank=True, verbose_name='date published')),
                ('url', models.URLField(blank=True, verbose_name='blog url')),
                ('thumburl', models.URLField(blank=True, verbose_name='thumbnail url')),
                ('text', models.TextField(blank=True, verbose_name='blog contents')),
                ('body', models.TextField(blank=True, verbose_name='html contents')),
                ('originalID', models.CharField(blank=True, max_length=10, verbose_name='original ID')),
                ('name', models.CharField(default='Untitled', max_length=100, verbose_name='blog title')),
                ('solrID', models.CharField(blank=True, max_length=64, verbose_name='solrID')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.Source')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=30, verbose_name='tag')),
            ],
        ),
    ]
