# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateTimeField(blank=True, verbose_name='date published')),
                ('url', models.URLField(blank=True, verbose_name='blog url')),
                ('text', models.TextField(blank=True, verbose_name='blog contents')),
                ('htmltext', models.TextField(blank=True, verbose_name='html contents')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='', max_length=30, verbose_name='tag')),
            ],
        ),
        migrations.AddField(
            model_name='blogposts',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.Tags'),
        ),
    ]
