# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0003_auto_20171207_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogposts',
            name='tag',
        ),
    ]
