# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0004_remove_blogposts_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogposts',
            old_name='htmltext',
            new_name='body',
        ),
        migrations.AddField(
            model_name='blogposts',
            name='name',
            field=models.TextField(default='Untitled', verbose_name='blog title'),
        ),
        migrations.AddField(
            model_name='blogposts',
            name='originalID',
            field=models.CharField(blank=True, max_length=10, verbose_name='original ID'),
        ),
    ]
