# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0005_auto_20171208_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pubdate', models.DateTimeField(blank=True, verbose_name='date published')),
                ('url', models.URLField(blank=True, verbose_name='blog url')),
                ('text', models.TextField(blank=True, verbose_name='blog contents')),
                ('body', models.TextField(blank=True, verbose_name='html contents')),
                ('originalID', models.CharField(blank=True, max_length=10, verbose_name='original ID')),
                ('name', models.CharField(default='Untitled', max_length=100, verbose_name='blog title')),
            ],
        ),
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
        migrations.DeleteModel(
            name='BlogPosts',
        ),
    ]
