# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0006_auto_20171208_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pubdate',
            field=models.CharField(blank=True, max_length=50, verbose_name='date published'),
        ),
    ]
