# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0008_blogpost_thumburl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='pubdate',
            field=models.DateTimeField(blank=True, verbose_name='date published'),
        ),
    ]
