# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0009_auto_20171208_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='solrID',
            field=models.CharField(blank=True, max_length=64, verbose_name='solrID'),
        ),
    ]
