# in working directory, copy this file; make 2 folders:
# 	mkdir configs
#	mkdir solrdata
# docker-compose up -d
# then log into sleuth terminal
# and you can launch the server
# python wwwsearch/manage.py runserver 0:8000


version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
#    restart: always
    ports:
      - '6379:6379'
#      - 8983:8983
#    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - $PWD/redis_data:/data
      
  sleuth:
    image: stephengrey1/sleuth:v0.2
    command: bash -c "python wwwsearch/manage.py migrate && python wwwsearch/manage.py runserver 0:8000"
    ports:
      - 8000:8000
    volumes:
      - ~/Documents:/data  #IMPORTANT THIS IS HOST FOLDER THAT SLEUTH CAN SCAN AND INDEX 
      - $PWD/configs:/var/sleuth #LOCATION TO STORE CONFIG FILES - MODIFY AND THEN RELAUNCH SLEUTH SERVER
      - $PWD/solrdata:/var/solr #LOCATION ON HOST TO STORE SOLR INDEXES
      
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    
  solr:
    image: stephengrey1/sleuth-solr
#solr:8.7
    ports:
      - 8983:8983
    volumes:
      - $PWD/solrdata:/var/solr
volumes:
  cache:
    driver: local
    
    
