# SETUP
#1. MAKE FOLDERS
#in working directory, copy this file; make 2 folders:
# 	mkdir configs
#	mkdir solrdata
#2. START SERVICES
# docker-compose up -d
#(to issue direct commands, you can use:
# docker compose exec sleuth bash
#)
#3. COPY DEFAULT INDEX AND SETTINGS
# docker compose exec -it sleuth bash -c ". /apps/copy_defaults.sh"
# docker compose restart solr
#4. SETUP DEFAULT PASSWORDS AND EMPTY INDEX
# docker compose exec -d sleuth bash -c "python wwwsearch/manage.py setup"
# (run this twice - first to set up passwords; then indexes)
#5. LAUNCH SERVER
# docker compose exec -d sleuth bash -c "python wwwsearch/manage.py runserver 0:8000"
# then log into sleuth terminal
# and you can launch the server
# http://localhost:8000


version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
#    restart: always
    ports:
      - '6379:6379'
#      - 8983:8983
#    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - $PWD/redis_data:/data
      
  sleuth:
    image: stephengrey1/sleuth:0.4
#    command: bash -c "python wwwsearch/manage.py migrate && python wwwsearch/manage.py runserver 0:8000"
    ports:
      - 8000:8000
    volumes:
      - ~/Documents:/data  #IMPORTANT THIS IS HOST FOLDER THAT SLEUTH CAN SCAN AND INDEX 
      - $PWD/configs:/var/sleuth #LOCATION TO STORE CONFIG FILES - MODIFY AND THEN RELAUNCH SLEUTH SERVER
      - $PWD/solrdata:/var/solr #LOCATION ON HOST TO STORE SOLR INDEXES
      
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    
  solr:
    image: stephengrey1/sleuth-solr
#solr:8.7
    ports:
      - 8983:8983
    volumes:
      - $PWD/solrdata:/var/solr
volumes:
  cache:
    driver: local
    
    
