# Generated by Django 2.1.7 on 2023-07-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagetext', models.CharField(blank=True, default='', max_length=65536, verbose_name='Message')),
                ('from_number', models.CharField(default='', max_length=30, verbose_name='From')),
                ('to_number', models.CharField(default='', max_length=30, verbose_name='To')),
                ('messagetype', models.CharField(default='WhatsApp', max_length=30, verbose_name='Message_Type')),
                ('message_source', models.CharField(default='', max_length=30, verbose_name='Source')),
                ('whatsapp_group', models.CharField(default='', max_length=60, verbose_name='Group')),
                ('attachments_number', models.IntegerField(default=0, verbose_name='Attachments')),
                ('attach1_path', models.CharField(default='', max_length=200, verbose_name='Attach1')),
                ('attach2_path', models.CharField(default='', max_length=200, verbose_name='Attach2')),
                ('send_time', models.DateTimeField(blank=True, verbose_name='Sent')),
                ('personal', models.BooleanField(default=False, verbose_name='Personal')),
                ('original_ID', models.CharField(default='', max_length=10, verbose_name='Original_ID_')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=30, verbose_name='Number')),
                ('name', models.CharField(default='', max_length=60, verbose_name='Name')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('personal', models.BooleanField(default=False, verbose_name='Personal')),
                ('photo_path', models.CharField(default='', max_length=200, verbose_name='PhotoPath')),
                ('name_exmessage', models.CharField(default='', max_length=200, verbose_name='Name in Message')),
                ('name_source', models.CharField(default='', max_length=30, verbose_name='Name source')),
                ('name_possible', models.CharField(default='', max_length=30, verbose_name='Possible name')),
                ('original_ID', models.CharField(default='', max_length=10, verbose_name='Original_ID_')),
                ('notes', models.CharField(default='', max_length=250, verbose_name='Notes')),
            ],
        ),
    ]
