# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-04 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messagetext', models.CharField(blank=True, default='', max_length=65536, verbose_name='Message')),
                ('from_number', models.CharField(default='', max_length=30, verbose_name='From')),
                ('to_number', models.CharField(default='', max_length=30, verbose_name='To')),
                ('send_time', models.DateTimeField(blank=True, verbose_name='Sent')),
                ('personal', models.BooleanField(default=False, verbose_name='Personal')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='', max_length=30, verbose_name='Number')),
                ('name', models.CharField(default='', max_length=30, verbose_name='Name')),
                ('verified', models.BooleanField(default=False, verbose_name='Verified')),
                ('name_exmessage', models.CharField(default='', max_length=30, verbose_name='Name in Message')),
                ('name_source', models.CharField(default='', max_length=30, verbose_name='Name source')),
                ('name_possible', models.CharField(default='', max_length=30, verbose_name='Possible name')),
            ],
        ),
    ]
