# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='whatsapp_group',
            field=models.CharField(default='', max_length=60, verbose_name='Group'),
        ),
    ]
