# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_message_whatsapp_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='original_ID',
            field=models.CharField(default='', max_length=10, verbose_name='Original_ID_'),
        ),
    ]
