# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-11 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0003_message_original_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='notes',
            field=models.CharField(default='', max_length=250, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='original_ID',
            field=models.CharField(default='', max_length=10, verbose_name='Original_ID_'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='name',
            field=models.CharField(default='', max_length=60, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='name_exmessage',
            field=models.CharField(default='', max_length=200, verbose_name='Name in Message'),
        ),
    ]
