# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepath', models.FilePathField(path='/Volumes/Crypt/OwnCloud', recursive=True, verbose_name='File path')),
                ('indexedSuccess', models.BooleanField(default=False, verbose_name='IndexedOK')),
                ('indexedTry', models.BooleanField(default=False, verbose_name='IndexedTry')),
                ('hash_contents', models.CharField(default='', max_length=200, verbose_name='Hash contents')),
                ('hash_filename', models.CharField(default='', max_length=200, verbose_name='Hash doc name')),
                ('filesize', models.IntegerField(default=0, verbose_name='Filesize')),
                ('last_modified', models.DateTimeField(verbose_name='date modified')),
            ],
        ),
        migrations.AlterField(
            model_name='collection',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=150, path='/Volumes/Crypt/OwnCloud', recursive=True, verbose_name='File path'),
        ),
        migrations.AddField(
            model_name='file',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Collection'),
        ),
    ]
