# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20170815_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='fileext',
            field=models.CharField(default='', max_length=10, verbose_name='File Extension'),
        ),
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default='', max_length=100, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='file',
            name='last_modified',
            field=models.DateTimeField(blank=True, verbose_name='date modified'),
        ),
    ]
