# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20170818_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=150, path=b'/Users/Stephen/', recursive=True, verbose_name='File path'),
        ),
    ]
