# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-24 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20170824_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filepath',
            field=models.FilePathField(path=b'/Users/Stephen/', recursive=True, verbose_name='File path'),
        ),
    ]
