# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20170828_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='solrid',
            field=models.CharField(default='', max_length=100, verbose_name='Solr ID'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=150, path=b'/home/ubuntu/docstore', recursive=True, verbose_name='File path'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filepath',
            field=models.FilePathField(path=b'/home/ubuntu/docstore', recursive=True, verbose_name='File path'),
        ),
    ]
