# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('documents', '0010_auto_20170907_0642'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolrCore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreID', models.CharField(default='', max_length=10, verbose_name='Core ID (1-10)')),
                ('coreDisplayName', models.CharField(blank=True, default='', max_length=10, verbose_name='Core Display Name')),
                ('usergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
    ]
