# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_solrcore'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='core',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.SolrCore'),
            preserve_default=False,
        ),
    ]
