# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_collection_core'),
        ('documents', '0011_auto_20170908_0847'),
    ]

    operations = [
    ]
