# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_merge_20170915_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='indexUpdateMeta',
            field=models.BooleanField(default=False, verbose_name='UpdateMeta'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=150, path=b'/Volumes/Crypt/ownCloud/', recursive=True, verbose_name='File path'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filepath',
            field=models.FilePathField(path=b'/Volumes/Crypt/ownCloud/', recursive=True, verbose_name='File path'),
        ),
    ]
