# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_solrcore_corename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceDisplayName', models.CharField(blank=True, default='', max_length=30, verbose_name='Core Display Name')),
                ('sourcename', models.CharField(default='', max_length=10, verbose_name='Corename')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Collection')),
            ],
        ),
        migrations.AlterField(
            model_name='solrcore',
            name='coreDisplayName',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Core Display Name'),
        ),
    ]
