# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_auto_20180108_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='collection',
        ),
        migrations.AlterField(
            model_name='source',
            name='sourceDisplayName',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Source Display Name'),
        ),
        migrations.AlterField(
            model_name='source',
            name='sourcename',
            field=models.CharField(default='', max_length=10, verbose_name='Sourcename'),
        ),
    ]
