# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_collection_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.Source'),
            preserve_default=False,
        ),
    ]
