# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_auto_20180117_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useredit',
            name='user',
        ),
        migrations.AddField(
            model_name='useredit',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='User ID'),
        ),
    ]
