# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_auto_20180117_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='useredit',
            name='time_modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time modified'),
        ),
        migrations.AlterField(
            model_name='useredit',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='user name'),
        ),
    ]
