# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_auto_20180117_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='useredit',
            name='corename',
            field=models.CharField(default='', max_length=20, verbose_name='Corename'),
        ),
    ]
