# Generated by Django 2.0.2 on 2018-03-02 10:17

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('documents', '0026_auto_20180213_0743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SolrCore',
            new_name='Index',
        ),
    ]
