# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-22 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('documents', '0026_auto_20180213_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreDisplayName', models.CharField(blank=True, default='', max_length=30, verbose_name='Core Display Name')),
                ('corename', models.CharField(default='', max_length=20, verbose_name='Corename')),
                ('usergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.RemoveField(
            model_name='solrcore',
            name='usergroup',
        ),
        migrations.AlterField(
            model_name='collection',
            name='core',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Index'),
        ),
        migrations.DeleteModel(
            name='SolrCore',
        ),
    ]
