# Generated by Django 2.0.6 on 2018-08-04 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('documents', '0027_auto_20180227_0615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coreDisplayName', models.CharField(blank=True, default='', max_length=30, verbose_name='Core Display Name')),
                ('corename', models.CharField(default='', max_length=20, verbose_name='Corename')),
                ('usergroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_useredit_lastid', models.IntegerField(default=1, verbose_name='Last imported edit id')),
            ],
        ),
        migrations.RemoveField(
            model_name='solrcore',
            name='usergroup',
        ),
        migrations.AddField(
            model_name='file',
            name='is_folder',
            field=models.BooleanField(default=False, verbose_name='IsFolder'),
        ),
        migrations.AddField(
            model_name='useredit',
            name='index_updated',
            field=models.BooleanField(default=False, verbose_name='Index Updated'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='core',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.Index'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=150, path='/Volumes/Crypt/ownCloud', recursive=True, verbose_name='File path'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filepath',
            field=models.FilePathField(path='/Volumes/Crypt/ownCloud', recursive=True, verbose_name='File path'),
        ),
        migrations.DeleteModel(
            name='SolrCore',
        ),
    ]
