# Generated by Django 2.0.6 on 2018-06-29 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_index_coreid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='coreID',
        ),
    ]
