# Generated by Django 2.0.6 on 2018-07-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_remove_index_coreid'),
    ]

    operations = [
        migrations.AddField(
            model_name='useredit',
            name='index_updated',
            field=models.BooleanField(default=False, verbose_name='Index Updated'),
        ),
    ]
