# Generated by Django 2.0.6 on 2018-07-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_syncstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_folder',
            field=models.BooleanField(default=False, verbose_name='IsFolder'),
        ),
        migrations.AlterField(
            model_name='syncstatus',
            name='remote_useredit_lastid',
            field=models.IntegerField(default=1, verbose_name='Last imported edit id'),
        ),
    ]
