# Generated by Django 2.1 on 2018-08-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0032_auto_20180729_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=150, path='R:\\CLOUD LOCAL\\OwnCloud_sgrey\\Malta-Share\\', recursive=True, verbose_name='File path'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filepath',
            field=models.FilePathField(path='R:\\CLOUD LOCAL\\OwnCloud_sgrey\\Malta-Share\\', recursive=True, verbose_name='File path'),
        ),
    ]
