# Generated by Django 2.0.6 on 2018-09-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0033_auto_20180827_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='content date'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='path',
            field=models.FilePathField(allow_files=False, allow_folders=True, max_length=150, path='/Volumes/Crypt/ownCloud/', recursive=True, verbose_name='File path'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filepath',
            field=models.FilePathField(path='/Volumes/Crypt/ownCloud/', recursive=True, verbose_name='File path'),
        ),
    ]
