# Generated by Django 2.1.5 on 2019-03-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0034_auto_20180918_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='indexedFlag',
        ),
        migrations.AddField(
            model_name='collection',
            name='live_update',
            field=models.BooleanField(default=False, verbose_name='Live update'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Error Message'),
        ),
        migrations.AddField(
            model_name='file',
            name='oldpaths_to_delete',
            field=models.TextField(blank=True, null=True, verbose_name='Old paths'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(default='', max_length=300, verbose_name='Filename'),
        ),
    ]
