# Generated by Django 2.0.6 on 2018-12-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0035_file_oldpaths_to_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='error_messsage',
            field=models.TextField(blank=True, null=True, verbose_name='Error Message'),
        ),
    ]
