# Generated by Django 2.1 on 2018-12-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0036_file_error_messsage'),
        ('documents', '0035_auto_20181026_1630'),
    ]

    operations = [
    ]
