# Generated by Django 2.1.5 on 2019-02-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0037_auto_20190102_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='indexedFlag',
            new_name='live_update',
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(default='', max_length=300, verbose_name='Filename'),
        ),
    ]
