# Generated by Django 2.1 on 2019-01-30 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_auto_20190110_1732'),
    ]

    operations = [
    ]
