# Generated by Django 2.1.5 on 2019-03-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0038_auto_20190215_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='live_update',
            field=models.BooleanField(verbose_name='Live update'),
        ),
    ]
