# Generated by Django 2.1 on 2019-03-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0039_merge_20190130_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='indexedFlag',
        ),
        migrations.AddField(
            model_name='collection',
            name='live_update',
            field=models.BooleanField(default=False, verbose_name='Live update'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(default='', max_length=300, verbose_name='Filename'),
        ),
    ]
